---
  - name: Install Apache Web server
    hosts: all
    become: yes

    tasks:

      - name: Install Apache Web Server
        yum:
          name   = httpd
          state  = latest    # state = install

      - name: Start Apache and enable every boot
        service:
          name   = httpd
          state  = started
          enable = yes
