---
  - name: Install Apache and Upload Web Server
    hosts: all
    become: yes

    vars:
      source_folder = /home/administrator
      destin_folder  = /var/www/html

    tasks:

    - name: Linux OS Family
      debug:
        var: ansible_os_family

    - block: ======> Setting for RedHat <===========
        - name: Install Apache Web Server for RedHat
          yum:
            name   = httpd
            state  = latest    # state = install



        - name: Start Apache and enable every boot for RedHat
          service:
            name   = httpd
            state  = started
            enable = yes

      when: ansible_os_family == "RedHat"   # Выплнять этот скрипт когда OS = RedHat



    - block: ======> Setting for Debian <===========
        - name: Install Apache Web Server for Debian
          apt:
            name   = apache2
            state  = latest

        - name: Start Apache and enable every boot for Debian
          service:
            name   = apache2
            state  = started
            enable = yes

      when: ansible_os_family == "Debian"   # Выплнять этот скрипт когда OS = Debian

# Вариант 1 с loop
    - name: Copy web-server.html
      copy:
        src = {{ source_folder }}/{{ item }}   #копировать все файлы указанные в loop
        dst = {{ destin_folder }}
      loop:
        - "index.html"
        - "examle.png"
        - "example2.png"
      notify:
        - "Restart Apache for RedHat"
        - "Restart Apache for Debian"

# Вариант 2 с with_fileglob
    - name: Copy web-server.html
      copy:
        src = {{ item }}   #копировать все файлы из папки
        dst = {{ destin_folder }}
      with_fileglob:
        - "{{ source_folder }}/*.*"
      notify:
        - "Restart Apache for RedHat"
        - "Restart Apache for Debian"


    handlers:
      - name: Restart Apache for RedHat
        service:
          name   = httpd
          state  = restart
        when: ansible_os_family == "RedHat"

      - name: Restart Apache for Debian
        service:
          name  = apache2
          state = restart
        when: ansible_os_family == "Debian"
