---
# handlers file for my_web_site

- name: Restart Apache for RedHat
  service:
    name:  httpd
    state: restart
  when: ansible_os_family == "RedHat"

- name: Restart Apache for Debian
  service:
    name:  apache2
    state: restart
  when: ansible_os_family == "Debian"
