---
# tasks file for my_web_site

- name: Linux OS Family
  debug:
    var: ansible_os_family

- block: ======> Setting for RedHat <===========
    - name: Install Apache Web Server for RedHat
      yum:
        name:  httpd
        state: latest    # state = install

    - name: Start Apache and enable every boot for RedHat
      service:
        name:   httpd
        state:  started
        enable: yes
  when: ansible_os_family == "RedHat"   # Выплнять этот скрипт когда OS = RedHat


- block: ======> Setting for Debian <===========
    - name: Install Apache Web Server for Debian
      apt:
        name:  apache2
        state: latest

    - name: Start Apache and enable every boot for Debian
      service:
        name:   apache2
        state:  started
        enable: yes
  when: ansible_os_family == "Debian"   # Выплнять этот скрипт когда OS = Debian


- name: Upload generated index.html
  template:
    src: index.j2
    dst: {{ destin_folder }}/index.html
  notify:
    - "Restart Apache for RedHat"
    - "Restart Apache for Debian"


- name: Copy web-server.html
  copy:
    src: {{ item }}   #копировать все файлы указанные в loop
    dst: {{ destin_folder }}
  loop:
    - "examle.png"
    - "example2.png"
  notify:
    - "Restart Apache for RedHat"
    - "Restart Apache for Debian"
