---
  - name: Install Apache and Upload Web Server
    hosts: all
    become: yes

    vars:
      source_files = /home/administrator/web_server.html
      destin_file  = /var/www/html

    tasks:

      - name: Linux OS Family
        debug:
          var: ansible_os_family

      - block: ======> Setting for RedHat <===========
          - name: Install Apache Web Server for RedHat
            yum:
              name   = httpd
              state  = latest    # state = install

          - name: Copy web-server.html
            copy:
              src = {{ source_files }}
              dst = {{ destin_file }}
            notify: Restart Apache for RedHat

          - name: Start Apache and enable every boot for RedHat
            service:
              name   = httpd
              state  = started
              enable = yes

        when: ansible_os_family == "RedHat"   # Выплнять этот скрипт когда OS = RedHat



      - block: ======> Setting for Debian <===========
          - name: Install Apache Web Server for Debian
            apt:
              name   = apache2
              state  = latest

          - name: Copy web-server.html
            copy:
              src = {{ source_files }}
              dst = {{ destin_file }}
            notify: Restart Apache for Debian

          - name: Start Apache and enable every boot for Debian
            service:
              name   = apache2
              state  = started
              enable = yes

        when: ansible_os_family == "Debian"   # Выплнять этот скрипт когда OS = Debian


    handlers:
      - name: Restart Apache for RedHat
        service:
          name   = httpd
          state  = restart
        when: ansible_os_family == "RedHat"

      - name: Restart Apache for Debian
        service:
          name  = apache2
          state = restart
        when: ansible_os_family == "Debian"
